### ISSUE TITLE
Webpack overwriting the _webpack.template.wrapper.twig

### ISSUE THREAD

**Issue by cclaro** [MilesHerndon/craft-webpack-project-boilerplate#1]
Hi there,

first of all great boilerplate!!
quick question, I am trying to change a bit the markup structure on the _webpack.template.wrapper.twig however every time the I re-run the watch it get overwritten.

Is there anything that I can do to stop that or am I missing any settings changes that I suppose to do?

Thanks!

**Comment by marker004** [comment]
Hey @cclaro. You can make any necessary outer wrapper adjustments to the wrapper template located in /src/webpack.templates/.

**Comment by cclaro** [comment]
Thanks!!
